# Use an official Nginx image as a base image
FROM nginx:alpine

# Copy the content of the local 'src' directory to the '/usr/share/nginx/html' directory in the container
COPY ./index.html /usr/share/nginx/html/

# Expose port 80
EXPOSE 80
